import type { Metadata } from "next";

import "./globals.css";
import NavbarMenu from "@/components/navbar";
import SiteFooter from "@/components/ui/footer";

export const metadata: Metadata = {
  title: "Briefly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark" >
        <NavbarMenu />
          {children}
          <SiteFooter />
      </body>
    </html>
  );
}

